apiVersion: v1
kind: Service
metadata:
  name: agh-website-dev
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: agh-website-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agh-website-dev
spec:
  selector:
    matchLabels:
      app: agh-website-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: agh-website-dev
    spec:
      containers:
      - name: agh-website-dev
        image: registry.gitlab.com/enlighten1/agh-targi-pracy-website:latest-development
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "80Mi"
            cpu: "20m"
          limits:
            memory: "250Mi"
            cpu: "200m"

      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: agh-website-dev-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts: 
    - targi-agh.enl-projects.com
    secretName: agh-website-dev-tls
  rules:
  - host: targi-agh.enl-projects.com
    http:
      paths:
      - backend:
          serviceName: agh-website-dev
          servicePort: 80
